from PIL import Image
from collections import deque

SRC="/Users/hamster/Desktop/食われる前の形.png"
BODY_H = 70          # target apple body height on the 240x135 LCD

im=Image.open(SRC).convert("RGBA"); w,h=im.size; px=im.load()
mask=Image.new("L",(w,h),0); mp=mask.load()
for y in range(h):
    for x in range(w):
        r,g,b,a=px[x,y]
        if a>128 and (r+g+b)/3<200: mp[x,y]=255

# components -> body (largest) and leaf
m=[[mp[x,y]>0 for x in range(w)] for y in range(h)]
seen=[[False]*w for _ in range(h)]; comps=[]
for y in range(h):
    for x in range(w):
        if m[y][x] and not seen[y][x]:
            q=deque([(y,x)]); seen[y][x]=True; pts=[]
            while q:
                cy,cx=q.popleft(); pts.append((cy,cx))
                for dy,dx in ((1,0),(-1,0),(0,1),(0,-1)):
                    ny,nx=cy+dy,cx+dx
                    if 0<=ny<h and 0<=nx<w and m[ny][nx] and not seen[ny][nx]:
                        seen[ny][nx]=True; q.append((ny,nx))
            comps.append(pts)
comps.sort(key=len,reverse=True)
bodyPts, leafPts = comps[0], comps[1]
bx=[p[1] for p in bodyPts]; by=[p[0] for p in bodyPts]
BX0,BX1,BY0,BY1=min(bx),max(bx),min(by),max(by)
lx=[p[1] for p in leafPts]; ly=[p[0] for p in leafPts]
LX0,LX1,LY0,LY1=min(lx),max(lx),min(ly),max(ly)

UX0,UX1 = min(BX0,LX0), max(BX1,LX1)
UY0,UY1 = min(BY0,LY0), max(BY1,LY1)
s = BODY_H/(BY1-BY0+1)
W = round((UX1-UX0+1)*s); H = round((UY1-UY0+1)*s)

small = mask.crop((UX0,UY0,UX1+1,UY1+1)).resize((W,H), Image.LANCZOS)
sp=small.load()
bits=[[1 if sp[x,y]>=128 else 0 for x in range(W)] for y in range(H)]

BODY_X0 = round((BX0-UX0)*s)
BODY_Y0 = round((BY0-UY0)*s)
BODY_W  = round((BX1-BX0+1)*s)

# bite circle, from the fit on the bitten reference
BITE_CX = BODY_X0 + 1.1019*BODY_W
BITE_CY = BODY_Y0 + 0.3808*BODY_H
BITE_R  = 0.2690*BODY_W

print("bitmap %dx%d  body_x0=%d body_y0=%d body_w=%d body_h=%d"%(W,H,BODY_X0,BODY_Y0,BODY_W,BODY_H))
print("bite cx=%.2f cy=%.2f r=%.2f"%(BITE_CX,BITE_CY,BITE_R))

stride=(W+7)//8
rows=[]
for y in range(H):
    bs=bytearray(stride)
    for x in range(W):
        if bits[y][x]: bs[x>>3] |= (0x80>>(x&7))
    rows.append(bs)

out=[]
out.append("// Auto-generated by tools/gen_apple.py from references/apple_whole.png")
out.append("// 1bpp packed bitmap, MSB first, each row padded to a byte boundary.")
out.append("#pragma once")
out.append("#include <stdint.h>")
out.append("")
out.append("static const int  APPLE_BMP_W       = %d;"%W)
out.append("static const int  APPLE_BMP_H       = %d;"%H)
out.append("static const int  APPLE_BMP_STRIDE  = %d;"%stride)
out.append("// apple body (excluding the leaf) inside the bitmap")
out.append("static const int  APPLE_BODY_X0     = %d;"%BODY_X0)
out.append("static const int  APPLE_BODY_Y0     = %d;"%BODY_Y0)
out.append("static const int  APPLE_BODY_W      = %d;"%BODY_W)
out.append("static const int  APPLE_BODY_H      = %d;"%BODY_H)
out.append("// bite circle fitted to references/apple_bitten.png (residual < 0.7px)")
out.append("static const float APPLE_BITE_CX    = %.2ff;"%BITE_CX)
out.append("static const float APPLE_BITE_CY    = %.2ff;"%BITE_CY)
out.append("static const float APPLE_BITE_R     = %.2ff;"%BITE_R)
out.append("")
out.append("static const uint8_t APPLE_BMP[%d] = {"%(stride*H))
for y,bs in enumerate(rows):
    out.append("  " + ", ".join("0x%02X"%b for b in bs) + ("," if y<H-1 else "") + "  // %d"%y)
out.append("};")
open("AppleBitmap.h","w").write("\n".join(out)+"\n")
print("wrote AppleBitmap.h (%d bytes of bitmap data)"%(stride*H))

# ---- previews ----
def render(bite_r):
    img=Image.new("RGB",(W,H),(0,0,0)); ip=img.load()
    for y in range(H):
        for x in range(W):
            if not bits[y][x]: continue
            if bite_r>0 and ((x+0.5-BITE_CX)**2+(y+0.5-BITE_CY)**2) <= bite_r*bite_r: continue
            ip[x,y]=(235,235,235)
    return img
render(0).resize((W*4,H*4), Image.NEAREST).save("preview_apple_whole.png")
render(BITE_R).resize((W*4,H*4), Image.NEAREST).save("preview_apple_bitten.png")
render(BITE_R*0.55).resize((W*4,H*4), Image.NEAREST).save("preview_apple_mid.png")
print("previews written")
